stages:
  - mirror-to-github

mirror-to-github:
  stage: mirror-to-github
  image: ubuntu:20.04
  script: |
    apt-get update
    apt-get install -yq --no-install-recommends ca-certificates git 
    mkdir .mirror
    cd .mirror
    git clone --bare https://gitlab.com/mattwiley/lz.git
    git push --mirror https://matt-wiley@github.com/matt-wiley/lz.git
