stages:
  - mirror-to-github
  - deploy

clone-bare-and-mirror:
  stage: mirror-to-github
  image: ubuntu:20.04
  script: |
    apt-get update
    apt-get install -yq --no-install-recommends ca-certificates git
    cd ci/
    ./mirror_to_github.sh "${GH_USERNAME}" "${GH_TOKEN}"

pages:
  stage: deploy
  image: ubuntu:20.04
  script: |
    cp -r .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
