name: Tests
on: 
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .vscode

jobs:
  run-tests:
    name: 🧪 Run Shellspec Tests
    runs-on: ubuntu-latest
    container:
      image: mattwiley/shellspec
    env:
      TEST_REPORT_PATH: report/results_junit.xml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Tests
        shell: bash
        env:
          HOME: /root # Correct the HOME env
          SKIP_CA_UPDATE: 0 # Enable CA updates so we can pull from GitHub
          BASE_URL: "https://raw.githubusercontent.com/matt-wiley/lz/${{ github.ref }}/"
        run: .scripts/test_runner.sh

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4.1.0
        with:
          check_name: '📑 Create Test Summary'
          report_paths: ${{ env.TEST_REPORT_PATH }}
          include_passed: true
          detailed_summary: true
          check_title_template: "{{TEST_NAME}}"
