name: Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: mattwiley/shellspec
      options: |
        -e HOME=/root
    steps:
      - uses: actions/checkout@v3
      - run: |
          shellspec --jobs 1 --format documentation
