name: Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: mattwiley/shellspec
    steps:
      - uses: actions/checkout@v3
      - run: |
          export HOME=/root
          export SKIP_CA_UPDATE=0 # Enable CA updates so we can pull from GitHub
          .scripts/test_runner.sh
