name: Tests
on: 
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .vscode

jobs:
  run-tests:
    name: Run Shellspec Tests
    runs-on: ubuntu-latest
    container:
      image: mattwiley/shellspec
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Tests
        shell: bash
        run: |
          export HOME=/root # Correct the HOME env
          export SKIP_CA_UPDATE=0 # Enable CA updates so we can pull from GitHub
          .scripts/test_runner.sh
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: Test Results
          report_paths: 'report/results_junit.xml'
          include_passed: true
          detailed_summary: true